### ISSUE TITLE
不具合

### ISSUE THREAD

**Issue by EX-ZER0** [matsumo0922/PixiView-KMP#11]
ユーザーの投稿一覧を見ようとしたとき「エラーが発生しました　データがありません」と表示されて過去の投稿を見ることができなくなりました

**Comment by matsumo0922** [comment]
FANBOX側のAPIに変更があったようです。
以下のコミットで修正し、本日修正版を Google Play にサブミットしました。

26e8d54f6e895f7d9d28a033e982d6d279ebb34f
