### ISSUE TITLE
不具合

### ISSUE THREAD

**Issue by EX-ZER0** [matsumo0922/PixiView-KMP#14]
![Screenshot_20240813-040204](https://github.com/user-attachments/assets/bb2fa35c-3ac8-45d5-9caf-b8d06cbddba7)
画像の通りユーザーの投稿が「エラーが発生しました　データがありません」となって過去の投稿が見れなくなっています

**Comment by matsumo0922** [comment]
現在修正版となるv2.1.4を公開中です。
ご確認ください :pray:

https://play.google.com/store/apps/details?id=caios.android.fanbox
