### ISSUE TITLE
いいねといいね解除が出来ない

### ISSUE THREAD

**Issue by kitadai31** [matsumo0922/PixiView-KMP#16]
このアプリにおいて、投稿へのいいねといいねの解除ができない問題が起こっているので、報告させていただきます。

具体的には、いいねしていない状態でいいねボタンを押すと、いいねボタンが赤くなって数字が増えていいねされたように見えますが、実際にはいいねできていないという状況です。
いいねを押しても、投稿を開き直すといいねしていない状態に戻っており、念の為ブラウザから確認してもいいねされていません。
~~また、いいねを押すとなぜか同時に投稿がブックマークに保存されます。~~

一方で、既にいいねしている投稿のいいねボタンを押した場合は、何も起こらず、いいねの解除ができません。

アプリのバージョンは2.1.4 (39)です。
ただし、3か月ほど前にこちらのアプリを使い始めてからずっと同じなので、どのバージョンから起こっているのかはわかりません。
端末はPixel 3 (Android 14) を使用しています。(Android 11でも同様でした。)

お手数をおかけしますがよろしくお願いいたします。

**Comment by kitadai31** [comment]
> また、いいねを押すとなぜか同時に投稿がブックマークに保存されます。

こちらですが、よくよく考えたらいいねを押した投稿がアプリ内のブックマークにも同時に保存されるのはとても便利なので、これは仕様であるということに最近気が付きました。
大変失礼いたしました。(ボタンの動作が入れ替わっているのかもしれないと思っていました。)
今更ですみません。

**Comment by matsumo0922** [comment]
@kitadai31 

返事が遅れて申し訳ありません。
仰っている通り「いいね」と「ブックマーク」は同時に行われる仕様となっています。

また、「いいね」については FANBOX に元から備わっている「いいね」機能と連動しているものであるため、FANBOX 側で「いいね」解除の機能が実装されない限り、こちらからは解除ができません。登録と解除をどちらも行いたい場合は「ブックマーク」機能をご利用ください 🙏 

ただし、現在「いいね」しても FANBOX 側と連携されない問題（FANBOX の Web ページで見たときにいいねされていない）が発生しています。こちらは次のバージョン 2.1.7 にて修正予定です。

https://github.com/matsumo0922/PixiView-KMP/blob/bbc00bf79eef78f1d9b2df20c30e4d41bce20a47/core/ui/src/commonMain/kotlin/me/matsumo/fanbox/core/ui/component/PostItem.kt#L378-L381

**Comment by kitadai31** [comment]
ご返信ありがとうございます。
確かに、公式のFANBOXでいいねを解除できるか試してみたところできませんでした。
確認不足で報告してしまい申し訳ありません。

いいねが反映されない問題は、次のバージョンで修正されるとのことで良かったです。
修正していただきありがとうございます！
