### ISSUE TITLE
不具合について

### ISSUE THREAD

**Issue by EX-ZER0** [matsumo0922/PixiView-KMP#18]
一部のユーザーの投稿が「エラーが発生しました データがありません」となっていて過去の投稿が閲覧できない状態になっています

**Comment by EX-ZER0** [comment]
pixiv id 2658856 
fanbox @fumihiko 
pixiv id 2502532 
fanbox @fuchitoro
の2名のクリエイターが見れない状態です
CAIOS IDとは何でしょうか

**Comment by matsumo0922** [comment]
原因が分かりましたので現在対応中です

**Comment by matsumo0922** [comment]
1194d7f5361881c7e1dd1cd04542741e24779eff で修正されました。
数日以内にリリースされる見込みです 👍
