### ISSUE TITLE
全ての投稿が見れなくなりました

### ISSUE THREAD

**Issue by EX-ZER0** [matsumo0922/PixiView-KMP#19]
どのユーザーの投稿も通信エラーとなって見ることができなくなりました
再読込しても状態が変わりません
アプリバージョン 2.1.4:40 [Premium]
カイオスID 3ad398c7-92fe-4170-bd33-545c79f5439d
FANBOXSESSID 6140872_YODCRCahewb6781yLeDG0jq0ewxgOQXh
CSRFトークン 4f9811a81f2a4a131e1bfe67427a9434

**Comment by matsumo0922** [comment]
状況を収集して対応中です

**Comment by matsumo0922** [comment]
@EX-ZER0 

FANBOXSESSID, CSRFトークンはユーザーのアカウントと結びつき得る機密情報のため、あまり公開しないようよろしくお願いします 🙏
