### ISSUE TITLE
ログインできなくなりました

### ISSUE THREAD

**Issue by EX-ZER0** [matsumo0922/PixiView-KMP#4]
デバイス名 Google Pixel4a(5G)
OSバージョン Android14
今月に入った途端画像の状態になっていてログインしても画像の状態に戻ってログイン状態が維持できなくなりました
![Screenshot_20240701-170959](https://github.com/matsumo0922/PixiView-KMP/assets/162322440/75d9204e-e19a-4b2a-9c36-84702a210da4)

**Comment by matsumo0922** [comment]
報告ありがとうございます。

2,3日前より、FANBOX 側でログインに対するセキュリティ要件が上がり、既存の実装ではログインに失敗しているようです。セキュリティ要件を満たせるよう変更を加えている最中ですので、しばらくお待ちください。

FYI: https://github.com/cromachina/fanbox-bot/issues/13
FYI: https://github.com/mikf/gallery-dl/issues/5791
FYI: https://github.com/Nandaka/PixivUtil2/issues/1342

**Comment by matsumo0922** [comment]
@EX-ZER0

#5 にて修正を完了しました。
#6 をマージしアプリのバージョンを「2.1.2」として Google Play にサブミット中です。

アプリが公開され次第、アップデートをお願いいたします。
ご報告ありがとうございました 🙏
